name: 'Download Source'
description: 'Download source from pypi or github'

inputs:
  name:
    description: 'Name of source'
    required: true
  version:
    description: 'Source version'
    required: false
    default: 'latest'
  platform:
    description: 'Platform to donwload, use pypi or github'
    required: false
    default: 'pypi'

runs:
  using: composite
  steps:
    - name: Download from pypi
      shell: bash
      if: ${{ inputs.platform == 'pypi' }}
      run: |
        DOWNLOAD_NAME="${{ inputs.name }}"
        DOWNLOAD_VERSION="${{ inputs.version }}"
        if [[ "${DOWNLOAD_VERSION}" == "latest" ]]; then
          DOWNLOAD_VERSION="$(curl -s https://pypi.org/pypi/${DOWNLOAD_NAME}/json | jq -r '.info.version')"
        fi
        DOWNLOAD_URL="$(curl -s https://pypi.org/pypi/${DOWNLOAD_NAME}/${DOWNLOAD_VERSION}/json | jq -r '.urls[] | select(.packagetype=="sdist") | .url')"
        echo "download version: ${DOWNLOAD_VERSION}"
        echo "download url: ${DOWNLOAD_URL}"
        wget -qO- ${DOWNLOAD_URL} | tar -zx --strip-components=1
        #wget -q ${DOWNLOAD_URL}
        echo "DOWNLOAD_NAME=${DOWNLOAD_NAME}-${DOWNLOAD_VERSION}" >> $GITHUB_ENV

    - name: Download from github
      shell: bash
      if: ${{ inputs.platform == 'github' }}
      run: |
        DOWNLOAD_REPO="${{ inputs.name }}"
        DOWNLOAD_NAME="$(echo ${DOWNLOAD_REPO} | cut -d '/' -f2)"
        DOWNLOAD_VERSION="${{ inputs.version }}"
        DOWNLOAD_URL="https://github.com/${DOWNLOAD_REPO}/archive/refs/tags/${DOWNLOAD_VERSION}.tar.gz"
        if [[ "${DOWNLOAD_VERSION}" == "latest" ]]; then
          DOWNLOAD_URL="https://github.com/${DOWNLOAD_REPO}/archive/refs/heads/main.tar.gz"
        fi
        echo "download version: ${DOWNLOAD_VERSION}"
        echo "download url: ${DOWNLOAD_URL}"
        #wget -q -O ${DOWNLOAD_NAME}-${DOWNLOAD_VERSION}.tar.gz ${DOWNLOAD_URL}
        wget -qO- ${DOWNLOAD_URL} | tar -zx --strip-components=1
        echo "DOWNLOAD_NAME=${DOWNLOAD_NAME}-${DOWNLOAD_VERSION}" >> $GITHUB_ENV

  post:
    - name: Clean downloaded files
      shell: bash
      run: |
        ls

