name: 'Download Source'
description: 'Download source from pypi or github'

inputs:
  name:
    description: 'Name of source'
    required: true
  version:
    description: 'Source version'
    required: false
    default: 'latest'
  platform:
    description: 'Platform to donwload, use pypi or github'
    required: false
    default: 'pypi'

runs:
  using: composite
  steps:
    - name: Download from pypi
      shell: bash
      if: ${{ inputs.platform == 'pypi' }}
      run: |
        DOWNLOAD_VERSION="${{ inputs.version }}"
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          DOWNLOAD_VERSION="$(curl -s https://pypi.org/pypi/${{ inputs.name }}/json | jq -r '.info.version')"
        fi
        echo $DOWNLOAD_VERSION
        DOWNLOAD_URL="$(curl -s https://pypi.org/pypi/${{ inputs.name }}/${DOWNLOAD_VERSION}/json | jq -r '.urls[] | select(.packagetype=="sdist") | .url')"
        echo $DOWNLOAD_URL
        wget $DOWNLOAD_URL

    - name: Download from github
      shell: bash
      if: ${{ inputs.platform == 'github' }}
      run: |
        DOWNLOAD_VERSION="${{ inputs.version }}"
        DOWNLOAD_URL="https://github.com/${{ inputs.name }}/archive/refs/tags/${DOWNLOAD_VERSION}.tar.gz"
        if [[ "${{ inputs.version }}" == "latest" ]]; then
          DOWNLOAD_URL="https://github.com/${{ inputs.name }}/archive/refs/heads/main.tar.gz"
        fi
        echo $DOWNLOAD_VERSION
        echo $DOWNLOAD_URL
        wget $DOWNLOAD_URL
