name: build free-threaded numpy wheel

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'latest'

jobs:
  build:
    name: Build wheel for numpy-${{ matrix.python }}-${{ matrix.platform }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [loongarch64-abi2.0]
        platform: ["manylinux", "musllinux"]
        python: ["cp313t"]
    steps:
      - name: Check if exists
        run: |
          pkg=numpy

          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            version="latest"
          else
            version="${{ github.event.inputs.version }}"
          fi

          platform="${{ matrix.platform }}"
          python_tag="${{ matrix.python }}"
          url="https://lpypi.loongnix.cn/loongson/pypi/+simple/${pkg}/"
          upstream_url="https://pypi.org/pypi/${pkg}/json"

          if [[ "${version}" == "latest" ]]; then
            version="$(curl -s ${upstream_url} | jq -r '.info.version')"
          fi

          if curl -s ${url} | grep ${version} | grep ${platform} | grep -q ${python_tag}; then
            echo "SKIP=true" >> $GITHUB_ENV
            echo "${platform} wheels already exists."
          else
            echo "SKIP=false" >> $GITHUB_ENV
            echo "${platform} wheels not found, continue building"
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Clean workspace
        if: ${{ env.SKIP != 'true' }}
        run: |
          safe-rm -rf * .*

      - name: Download source
        if: ${{ env.SKIP != 'true' }}
        uses: wxpppp/sources@main
        with:
          name: numpy
          version: ${{ env.VERSION }}

      - name: Disable build isolation for python free-threaded version
        if: ${{ endsWith(matrix.python, 't') && env.SKIP != 'true' }}
        shell: bash -el {0}
        run: |
          CIBW="pip; args: --no-build-isolation"
          echo "CIBW_BUILD_FRONTEND=$CIBW" >> "$GITHUB_ENV"

      - name: Build wheel
        if: ${{ env.SKIP != 'true' }}
        run: |
          cibuildwheel
        env:
          PIP_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
          PIP_EXTRA_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
          CIBW_ARCHS: "loongarch64"
          CIBW_BUILD: "${{ matrix.python }}-${{ matrix.platform }}_loongarch64"
          CIBW_ENABLE: cpython-freethreading
          CIBW_TEST_SKIP: "*"
          CIBW_ENVIRONMENT_PASS_LINUX: |
            PIP_INDEX_URL
            PIP_EXTRA_INDEX_URL

      - name: Upload wheels
        if: ${{ env.SKIP != 'true' }}
        run: |
          ls wheelhouse/*${{ matrix.python }}-${{ matrix.platform }}_*.whl || exit 1
          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*${{ matrix.python }}-${{ matrix.platform }}_*.whl
        env:
          TWINE_USERNAME: ${{ secrets.INDEX_NAME  }}
          TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
