name: build numba wheel

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'latest'

env:
  PACKAGE: numba
jobs:
  build:
    name: Build numba ${{ matrix.python }} ${{ matrix.platform }} wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [loongarch64-abi2.0]
        platform: ["manylinux"]
        python: ["cp310", "cp311", "cp312", "cp313"]
    steps:
      - name: Check if exists
        run: |
          pkg=${{ env.PACKAGE }}

          python_tag=${{ matrix.python }}

          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            version="latest"
          else
            version="${{ github.event.inputs.version }}"
          fi

          platform="${{ matrix.platform }}"
          url="https://lpypi.loongnix.cn/loongson/pypi/+simple/${pkg}/"
          upstream_url="https://pypi.org/pypi/${pkg}/json"

          if [[ "${version}" == "latest" ]]; then
            version="$(curl -s ${upstream_url} | jq -r '.info.version')"
          fi

          if curl -Ls ${url} | grep -q ${pkg}-${version}-.*${python_tag}-${platform}.*loongarch64; then
            echo "SKIP=true" >> $GITHUB_ENV
            echo "${platform} wheels already exists."
          else
            echo "SKIP=false" >> $GITHUB_ENV
            echo "${platform} wheels not found, continue building"
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Detect requirments
        if: ${{ env.SKIP != 'true' }}
        run: |
          if [[ "${{ matrix.python }}" == "cp313" ]]; then
              numpy_version="2.1.3"
          else
              numpy_version="2.0.2"
          fi
          echo "Using numpy version: ${numpy_version}"
          echo "NUMPY_VERSION=${numpy_version}" >> $GITHUB_ENV 

      - name: Clean workspace
        if: ${{ env.SKIP != 'true' }}
        run: |
          safe-rm -rf * .*

      - name: Download source
        if: ${{ env.SKIP != 'true' }}
        uses: wxpppp/sources@main
        with:
          name: ${{ env.PACKAGE }}
          version: ${{ env.VERSION }}

      - name: Build wheel
        if: ${{ env.SKIP != 'true' }}
        run: |
          pip3 install -i https://lpypi.loongnix.cn/loongson/pypi/+simple cibuildwheel==2.22.0
          cibuildwheel
        env:
          PIP_EXTRA_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
          PIP_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
          CIBW_BEFORE_BUILD: pip install numpy==${{ env.NUMPY_VERSION }} setuptools wheel llvmlite
          CIBW_ARCHS: "loongarch64"
          CIBW_BUILD: "${{ matrix.python }}-${{ matrix.platform }}_loongarch64"
          CIBW_ENVIRONMENT_PASS_LINUX: |
            PIP_INDEX_URL
            PIP_EXTRA_INDEX_URL

      - name: Upload wheels
        if: ${{ env.SKIP != 'true' }}
        run: |
          ls wheelhouse/*${{ matrix.python }}*-${{ matrix.platform }}_*.whl || exit 1
          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*${{ matrix.python }}*-${{ matrix.platform }}_*.whl
        env:
          TWINE_USERNAME: ${{ secrets.INDEX_NAME  }}
          TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}
