name: build numpy wheel


on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Download source
        uses: wxpppp/sources@main
        with:
          name: numpy
          version: ${{ github.event.inputs.version }}

      - name: Build wheel
        uses: wxpppp/cibuildwheel@2.22.0-loongarch64
        env:
          CIBW_ARCHS: "loongarch64"
          CIBW_BUILD: "*-manylinux_loongarch64"
          CIBW_TEST_SKIP: "*"

      - name: Clean up
        if: always()
        run: |
          ls
          
        



