name: build numpy wheel


on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Download source
        uses: wxpppp/sources@main
        with:
          name: numpy
          version: ${{ github.event.inputs.version }}

      - name: Build wheel
        run: |
          cibuildwheel
        env:
          PIP_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
          PIP_EXTRA_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"
          CIBW_ARCHS: "loongarch64"
          CIBW_BUILD: "*-manylinux_loongarch64"
          CIBW_TEST_SKIP: "*"
          CIBW_ENVIRONMENT_PASS_LINUX: |
            PIP_INDEX_URL
            PIP_EXTRA_INDEX_URL

      - name: Upload wheels
        run: |
          ls wheelhouse/*.whl || exit 0
          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/*.whl
        env:
          TWINE_USERNAME: ${{ secrets.INDEX_NAME  }}
          TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}

      - name: Clean up
        if: always()
        run: |
          rm -r *
          
        



